# App Info
ios_app_id                                : 6443526954                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                            # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : An Inspire
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : AI focusing on mobile techniques and improving customer impression of applications.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Knight Captain
your_link                                 : https://appai.fly.dev/kk/index.html
your_city                                 : CN
email_address                             : k-night@163.com
facebook_username                         :                                           
instagram_username                        : knight.captain
twitter_username                          : 
github_username                           : knight2010
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Inpiration Calendar & Reminder
    description                           : Support to manage the calendar and reminder data together in {ai} view.
    fontawesome_icon_name                 : calendar-alt
    
  - title                                 : Techniques Trends
    description                           : Recommend techniques podcast and awesome wwdc videos.
    fontawesome_icon_name                 : bed

  - title                                 : Awesome Widget
    description                           : Support different types of widgets.
    fontawesome_icon_name                 : chart-bar

  - title                                 : Light app clips
    description                           : Light fast showing living an-inspire.
    fontawesome_icon_name                 : th-large

  - title                                 : Siri commands
    description                           : Very user-friendly design.Specify intent by Siri.
    fontawesome_icon_name                 : user-astonaut

  - title                                 : An Inspire
    description                           : Fantastic way to implementate live activity, follow modern swift version.
    fontawesome_icon_name                 : atom

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0
topbar_title_color                        : "#000"

cover_image                               : #assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000"

link_color                                : "#f59500"

app_title_color                           : "#fff"
app_price_color                           : "#fff"
app_description_color                     : "#fff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#f59500"
feature_icons_background_color            : "#222"

social_icons_foreground_color             : "#f59500"
social_icons_background_color             : "#222"

footer_text_color                         : "#fff"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
